### PR TITLE
Update README.md for new documenation Link

### PR DESCRIPTION
**Pull request by anschaible**

### CODE REVIEW

**Comment by TobiBu** [comment]
@all-contributors please add @anschaible for Code, Content, Data, Documentation, Design, Examples, Ideas & Planning, Infrastructure, Maintenance, Plugin, Project Management, Answering Questions, Research, Review Pull Requests, Tools, Tests, Talks, User Testing

**Comment by TobiBu** [comment]
BTW: the tests are fixed by restricting the jax version to not use 0.4.36

**Comment by ufuk-cakir** [comment]
installed, do we need do write the comment again?

**Review by ufuk-cakir — APPROVED** [review]
think we need to merge this such that the bot starts working

**Comment by TobiBu** [comment]
@all-contributors please add @anschaible for Code, Content, Data, Documentation, Design, Examples, Ideas & Planning, Infrastructure, Maintenance, Plugin, Project Management, Answering Questions, Research, Review Pull Requests, Tools, Tests, Talks, User Testing

**Comment by TobiBu** [comment]
@all-contributors please add @ufuk-cakir for Code, Content, Data, Documentation, Design, Examples, Ideas & Planning, Infrastructure, Maintenance, Plugin, Project Management, Answering Questions, Research, Review Pull Requests, Tools, Tests, Talks, User Testing

**Comment by TobiBu** [comment]
@all-contributors please add @TobiBu for Code, Content, Data, Documentation, Design, Examples, Ideas & Planning, Infrastructure, Maintenance, Plugin, Project Management, Answering Questions, Research, Review Pull Requests, Tools, Tests, Talks, User Testing, Mentoring, Project Management

**Pull request merged**
